name: "Test typescript-action"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1

    - run: npm ci
    - run: npm run build
    - run: npm test
    - uses: ./
      with: 
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        persons: "rowi1de"
        # teams: "no-team"
        include-draft: false
        skip-with-manual-reviewers: 1
